/* libhop, the Hop client SDK + bearer contract. GENERATED by cbindgen; do not edit. */

#ifndef HOP_H
#define HOP_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Aggregate cap for variable-length byte slices crossing the C boundary. Larger application bodies
// must be chunked by the caller; fixed-width keys use tighter per-call caps below.
#define MAX_C_ABI_INPUT_BYTES ((16 * 1024) * 1024)

// Byte length written by [`hop_validate_wire_bundle`]. The layout is documented on that function.
#define HOP_WIRE_BUNDLE_METADATA_LEN 211

// The libhop C-ABI version. Bump on any signature or semantic change to an exported `hop_*`
// function. A wrapper should assert `hop_abi_version() == HOP_ABI_VERSION` at load so a wrapper
// built against a newer header fails loudly instead of drifting silently (F-28). This is the
// *ABI* version and is independent of the *wire* format version (bundle.rs `BUNDLE_VERSION`).
//
// v4 -> v5: added the §19 relay-pool calls (`hop_relay_add`, `hop_relay_next`,
// `hop_relay_report`, `hop_relay_pool_size`). Additive, so a v4 caller still links; what the bump
// buys is that a wrapper which binds those four calls cannot be paired at runtime with a v4
// library that does not export them, because the load-time assertion is `==`.
//
// PLAT-003: this note used to say the bump "is what lets a wrapper assert it can actually reach
// failover", which was false of every wrapper for as long as it stood. A version integer confers
// no capability; binding the symbols does, and no C-ABI wrapper bound them. The functions named
// in a bump note are now MACHINE-CHECKED against every wrapper pinned to that version by
// tools/codegen/check-abi-version.sh, so this paragraph can no longer describe a surface the
// wrappers do not expose.
//
// v5 -> v6: added the §32 `hps://` pub/sub surface, which the C ABI had no exports for at all, so
// every wrapper that sits on it (Swift, Kotlin, and the React Native bridge above them) could not
// reach group chat or channels even though the protocol has shipped in the two native UniFFI
// drivers for as long as it has existed. The calls are `hop_hps_register`, `hop_hps_subscribe`,
// `hop_hps_publish`, `hop_poll_hps_messages`, `hop_accept_hps_message`, `hop_hps_invite`,
// `hop_hps_accept_invite`, `hop_hps_decline_invite`, `hop_poll_hps_invites`, `hop_hps_leave`,
// `hop_hps_pending`, `hop_hps_approve`, `hop_hps_deny`, `hop_hps_rekey`, `hop_hps_reach`,
// `hop_hps_members`, `hop_hps_my_topics` and `hop_hps_browse`. Additive, so a v5 caller still
// links; the bump is what stops a wrapper that binds them being paired with a v5 library that does
// not export them, and what holds every wrapper to binding the whole surface (PLAT-003).
//
// v6 -> v7: added explicit service-request acceptance (`hop_accept_service_request`,
// `hop_reject_service_request`) and storage encryption inspection (`hop_node_is_encrypted`).
#define HOP_ABI_VERSION 7

// Which side opened a bearer link (the Noise role). Mirrors hop-core's internal `Role`.
typedef enum HopLinkRole {
    // We dialed out (BLE central / TCP connect / Wi-Fi inviter) → Noise initiator.
    HopLinkRole_Dialer = 0,
    // A peer connected in (peripheral / listener / invitee) → Noise responder.
    HopLinkRole_Acceptor = 1,
} HopLinkRole;

// The kind of `hps://` topic hosted at a path (DESIGN.md §32). Mirrors hop-core's `ServiceKind`.
typedef enum HopHpsKind {
    // Anyone with the content key reads AND writes; each publication signed by its writer.
    HopHpsKind_Channel = 0,
    // Only the owner broadcasts (signed by the service key); subscribers read.
    HopHpsKind_Service = 1,
} HopHpsKind;

// Who may obtain a topic's keys (DESIGN.md §32). Mirrors hop-core's `AccessMode`.
typedef enum HopHpsAccess {
    // Keys handed to anyone who asks (anonymous membership).
    HopHpsAccess_Open = 0,
    // Requester asks; the host approves before keys are handed off.
    HopHpsAccess_RequestToJoin = 1,
    // Host invites a destination; the destination accepts, then receives keys.
    HopHpsAccess_Invite = 2,
} HopHpsAccess;

// Whether a topic announces itself for discovery (DESIGN.md §32). Mirrors hop-core's `Visibility`.
typedef enum HopHpsVisibility {
    // Reachable only by a known address+path or an invite.
    HopHpsVisibility_Private = 0,
    // Host broadcasts an (app-encrypted) discovery advert so same-app peers can browse it.
    HopHpsVisibility_Discoverable = 1,
} HopHpsVisibility;

// A running Hop node the host drives. Thread-safe (interior `Mutex`), handed to
// the foreign side as a reference-counted object.
typedef struct HopNode HopNode;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the ABI version this shared library implements (see [`HOP_ABI_VERSION`]).
uint32_t hop_abi_version(void);

// Decode, verify, and canonically re-encode one complete bundle without constructing protocol state.
// On success, writes exactly [`HOP_WIRE_BUNDLE_METADATA_LEN`] bytes to `out_metadata`:
// `[version:1, destination:1, private:1, is_ack:1, wire_len_le:4, ciphertext_len_le:4,
// copies_le:2, hops:1, trace_len:1, created_at_le:8, lifetime_ms_le:4, hop_limit:1,
// id:32, private_content_id:32, recognition_tag:16, recognition_ephemeral:32,
// mailbox_present:1, mailbox:2, integrity_kind:1, signature_len_le:2, signature:64]`.
// `integrity_kind` is 0 for an Ed25519-signed bundle, 1 for a private wire ID, and 2 for a vaccine
// ID. Fields that do not apply are zero-filled. Returns false on invalid pointers or lengths,
// decode/verification failure, a non-canonical encoding, or an output buffer shorter than 211 bytes.
//
// `mailbox` is a FIXED 2-byte slot carrying a VARIABLE-WIDTH routing prefix, left-aligned and
// zero-padded. Its width is a privacy dial (`MAILBOX_ROUTE_PREFIX_BYTES`, which sets the recipient
// anonymity set and narrowed 2 -> 1 in wire v12). Keeping the SLOT fixed lets that dial turn without
// disturbing this published layout, so it costs no ABI bump and no SDK churn. Read
// `mailbox_present` first; the padding bytes are always zero.
bool hop_validate_wire_bundle(const uint8_t *bytes,
                              uintptr_t len,
                              uint8_t *out_metadata,
                              uintptr_t out_metadata_len);

// Open a node with persistent storage at `db_path` (UTF-8 C string), a saved 32-byte identity
// `secret` (pass NULL/0 for a fresh identity), and a 32-byte `app_secret` (NULL/0 = open fabric).
// Returns an owning handle to free with `hop_node_free`, or NULL on a NULL/non-UTF-8 `db_path`.
//
// If the db path exists but can't be opened it is quarantined and reopened fresh; only if that
// also fails does the node run with EPHEMERAL storage (call `hop_node_is_persistent` to detect
// this) rather than silently, and rather than NULL (F-26).
const struct HopNode *hop_node_open(const char *db_path,
                                    const uint8_t *secret,
                                    uintptr_t secret_len,
                                    const uint8_t *app_secret,
                                    uintptr_t app_secret_len);

// Like `hop_node_open`, but ENCRYPTS the store at rest with a raw `key` (typically 32 bytes) the host
// derives and stores in the platform Keychain/Keystore (F-25). Real encryption requires libhop to be
// built with the store's `sqlcipher` feature; builds without `sqlcipher` reject a non-empty key
// (fail closed) and return NULL. A NULL/empty key behaves like `hop_node_open`. NULL/non-UTF-8 `db_path` ⇒ NULL.
const struct HopNode *hop_node_open_keyed(const char *db_path,
                                          const uint8_t *secret,
                                          uintptr_t secret_len,
                                          const uint8_t *app_secret,
                                          uintptr_t app_secret_len,
                                          const uint8_t *key,
                                          uintptr_t key_len);

// Create a node with a fresh identity and ephemeral (in-memory) storage. Free with `hop_node_free`.
const struct HopNode *hop_node_new(void);

// Open a node from a saved 32-byte identity `secret` with ephemeral (in-memory) storage. Pass
// NULL/0 for a fresh identity. Free with `hop_node_free`.
const struct HopNode *hop_node_with_secret(const uint8_t *secret, uintptr_t secret_len);

// Whether this node has durable storage. Returns false when the db path was unusable and the
// node is running ephemerally (state will not survive a restart); the host should surface this
// rather than treat the database as ground truth (F-26). NULL handle ⇒ false.
bool hop_node_is_persistent(const struct HopNode *node);

// True only when the store is SQLCipher-keyed at rest (F-25, audit-001). NULL handle returns false.
bool hop_node_is_encrypted(const struct HopNode *node);

// How many persisted records failed to decode on startup (F-03). Non-zero ⇒ an upgrade changed
// a struct's on-disk layout and dropped that state; surface it to the user. NULL handle ⇒ 0.
uint32_t hop_node_rehydrate_dropped(const struct HopNode *node);

// Free a node handle returned by any constructor. Safe to pass NULL.
//
// Ownership: this consumes the one strong reference each constructor returned. The caller must
// ensure no other thread is calling into the same handle concurrently with free (the ABI does
// not expose a retain/clone), and must not use the pointer afterward.
void hop_node_free(const struct HopNode *node);

// Write this node's 32-byte address into `out` (must have room for 32 bytes). False on NULL.
bool hop_node_address(const struct HopNode *node, uint8_t *out);

// Write this node's 32-byte identity secret into `out` (room for 32 bytes) so the host can persist
// it (e.g. in the Keychain) and restore the node later with `hop_node_with_secret`/`hop_node_open`.
// Returns the number of bytes written (32), or 0 on NULL.
uintptr_t hop_node_secret(const struct HopNode *node, uint8_t *out);

// Set the display name this node reports via presence / `hop.identify` (DESIGN.md §29).
void hop_node_set_name(const struct HopNode *node, const char *name);

// Offer a relay endpoint to the pool. `configured` non-zero marks an operator/user choice, which
// a gossiped endpoint can never demote. Returns true if the endpoint is now pooled.
bool hop_relay_add(const struct HopNode *node, const char *url, bool configured);

// Write the relay the host should dial right now into `out` (`out_cap` bytes incl. NUL) and return
// its length. Returns 0 when there is nothing to dial, which means either an empty pool OR every
// candidate backed off; the latter is a WAIT-and-retry state, not permanent loss of reach. Use
// [`hop_relay_pool_size`] to tell them apart.
uintptr_t hop_relay_next(const struct HopNode *node, char *out, uintptr_t out_cap);

// Report a dial outcome so the pool can score it. A success clears that endpoint's failure
// history; failures back it off exponentially and always eventually recover.
void hop_relay_report(const struct HopNode *node, const char *url, bool ok);

// Total pooled endpoints, and how many are dialable right now, via `out_available` (may be NULL).
// `size > 0` with `available == 0` is the degraded "everything backed off" state a UI should show
// as such rather than as offline.
uintptr_t hop_relay_pool_size(const struct HopNode *node, uintptr_t *out_available);

// Advance authenticated protocol time: expire adverts, retransmit unacked bundles, and prune dedup.
// `now_ms` must be plausible, non-regressing Unix epoch milliseconds from synchronized wall time.
// Monotonic uptime counters such as Arduino `millis()` or `esp_timer_get_time()` are not Unix time.
void hop_node_tick(const struct HopNode *node, uint64_t now_ms);

// A bearer link came up. `role` = which side dialed (the Noise initiator/responder selector),
// using the [`HopLinkRole`] discriminants (0 = Dialer, 1 = Acceptor).
//
// core-ffi-05: `role` is taken as a plain `u32`, not the `HopLinkRole` enum by value. A C caller
// passing an out-of-range int would otherwise materialize an invalid Rust enum (instant UB) before
// any validation runs. Here only `0` selects Dialer; any other value is treated as Acceptor, so a
// bad int can never be UB.
void hop_link_up(const struct HopNode *node, uint64_t link, uint32_t role);

// One frame of opaque bytes arrived on `link`.
void hop_bytes_received(const struct HopNode *node,
                        uint64_t link,
                        const uint8_t *data,
                        uintptr_t len);

// A bearer link dropped.
void hop_link_down(const struct HopNode *node, uint64_t link);

// Drain queued outbound packets. Synchronously invokes `sink(ctx, link, bytes_ptr, bytes_len)`
// once per packet during this call. This is the POLL model; core never pushes asynchronously.
// The byte pointer is valid only for the duration of each `sink` call; copy what you keep.
void hop_drain_outgoing(const struct HopNode *node, void (*sink)(void *ctx,
                                                                 uint64_t link,
                                                                 const uint8_t *bytes,
                                                                 uintptr_t len), void *ctx);

// Subscribe the directory to a service `topic` (UTF-8 C string).
void hop_subscribe(const struct HopNode *node, const char *topic);

// Publish this node's prekey advert (DESIGN.md §25) so peers can seal forward-secret messages to
// us; it gossips on link-up. Call once after opening (and after the first `hop_node_tick` sets a
// real clock, else the advert is judged expired). Returns true on success.
bool hop_publish_prekey(const struct HopNode *node);

// Drain newly-received messages (poll model). Invokes
// `sink(ctx, inbox_id32, from32, content_type_cstr, body_ptr, body_len, hops, created_at_ms)` once
// per message during this call. `inbox_id` and `from` each point at 32 bytes; `content_type` is a
// NUL-terminated UTF-8 string; `body` is `body_len` bytes. All pointers are valid only for the
// callback. Returning true is synchronous host acceptance: core then durably removes that item and
// emits its ACK/vaccine. Returning false, exiting, or failing acceptance persistence leaves it queued
// for redelivery.
void hop_poll_inbox(const struct HopNode *node,
                    bool (*sink)(void *ctx,
                                 const uint8_t *inbox_id,
                                 const uint8_t *from,
                                 const char *content_type,
                                 const uint8_t *body,
                                 uintptr_t body_len,
                                 uint8_t hops,
                                 uint64_t created_at),
                    void *ctx);

// Durably accept one item previously returned by [`hop_poll_inbox`]. `inbox_id` points to exactly
// 32 bytes. Returns false for NULL, an unknown/already-accepted id, or a persistence failure.
bool hop_accept_inbox(const struct HopNode *node, const uint8_t *inbox_id);

// Send to a DIRECTLY-CONNECTED peer `dst` (32 bytes), sealed with the key learned at handshake
// (the directed §27 path; prefer `hop_send_message` unless you specifically want a directed send).
// On success writes the 32-byte bundle id to `out_id` (may be NULL) and returns true; false if not
// connected to that peer or on error.
bool hop_send_to(const struct HopNode *node,
                 const uint8_t *dst,
                 const char *content_type,
                 const uint8_t *body,
                 uintptr_t body_len,
                 bool request_ack,
                 uint8_t *out_id);

// Delivery status of a message we sent, by its 32-byte bundle `id`. Writes each field to its
// (nullable) out-param: `relayed` = distinct peers handed a copy; `delivered` = destination
// confirmed; `hops`/`ms` = the FORWARD-path (A→B) length + latency the destination reported (§39
// private ACK), 0 until delivered. Returns false on NULL node/id.
bool hop_message_status(const struct HopNode *node,
                        const uint8_t *id,
                        uint32_t *out_relayed,
                        bool *out_delivered,
                        uint8_t *out_hops,
                        uint32_t *out_ms);

// True iff messaging `addr` (32 bytes) is forward-secret: a ratchet session exists (DESIGN.md §25)
// rather than a static seal. Drives a lock indicator. False on NULL.
bool hop_is_secured(const struct HopNode *node, const uint8_t *addr);

// Send a hops:// service request to `dst` (32 bytes): invoke `method` on `service` with `args`.
// The reply arrives later via `hop_poll_service_responses`. Writes the 32-byte request id to
// `out_id` (may be NULL) and returns true.
bool hop_send_service_request(const struct HopNode *node,
                              const uint8_t *dst,
                              const char *service,
                              const char *method,
                              const uint8_t *args,
                              uintptr_t args_len,
                              uint8_t *out_id);

// Seal a hops:// response back to a request's caller (host side). `to` = the request's `from`;
// `for_request_id` = its `request_id`. Returns true on success.
bool hop_send_service_response(const struct HopNode *node,
                               const uint8_t *to,
                               const uint8_t *for_request_id,
                               uint16_t status,
                               const uint8_t *body,
                               uintptr_t body_len);

// Join the endpoint cluster keyed by the 32-byte `secret` (all replicas of one endpoint pass the
// same secret). `hop_send_service_response` marks a request complete for the siblings automatically;
// a fire-and-forget handler calls `hop_cluster_mark_done`. No-op if `secret` is null.
void hop_cluster_join(const struct HopNode *node,
                      const uint8_t *secret);

// Join the endpoint cluster from a passphrase (the 32-byte secret is derived from it): every replica
// given the same string joins the same cluster, across languages and the standalone service. This is
// the ergonomic entry point; `hop_cluster_join` takes a raw 32-byte secret. No-op if `pass` is null.
void hop_cluster_join_passphrase(const struct HopNode *node,
                                 const uint8_t *pass,
                                 uintptr_t pass_len);

// Explicit completion for a fire-and-forget handler (one that sends no response): mark request
// `(from32, request_id32)` handled and gossip it so sibling replicas drop their copies.
void hop_cluster_mark_done(const struct HopNode *node,
                           const uint8_t *from,
                           const uint8_t *request_id);

// Whether request `(from32, request_id32)` would be dropped as already handled by a sibling replica
// (introspection; the poll path applies this automatically). False if `node` is null or unclustered.
bool hop_cluster_would_drop(const struct HopNode *node,
                            const uint8_t *from,
                            const uint8_t *request_id);

// Live replica count (self + peers within the membership TTL); 1 if not clustered, 0 if `node` null.
uint32_t hop_cluster_members(const struct HopNode *node);

// Require at least `min_live_members` recently visible before processing. This TTL-based threshold
// is a conservative failover heuristic, not consensus or an at-most-once guarantee. `0` disables it.
void hop_cluster_set_quorum(const struct HopNode *node,
                            uint32_t min_live_members);

// Poll hops:// service requests addressed to this node (host side) without consuming them. Invokes
// `sink(ctx, from32, request_id32, service_cstr, method_cstr, args_ptr, args_len)` per request.
// Returning true is synchronous host acceptance. Returning false leaves the request queued for
// redelivery until [`hop_accept_service_request`] or [`hop_reject_service_request`] succeeds.
void hop_poll_service_requests(const struct HopNode *node,
                               bool (*sink)(void *ctx,
                                            const uint8_t *from,
                                            const uint8_t *request_id,
                                            const char *service,
                                            const char *method,
                                            const uint8_t *args,
                                            uintptr_t args_len),
                               void *ctx);

// Durably accept one request previously returned by [`hop_poll_service_requests`].
// `request_id` points to exactly 32 bytes. Returns false for NULL, an unknown/already-accepted
// request id, or a persistence failure.
bool hop_accept_service_request(const struct HopNode *node, const uint8_t *request_id);

// Reject one request previously returned by [`hop_poll_service_requests`] without ACK or dedup
// consumption so a retransmission can retry. Returns false for NULL or an unknown request id.
bool hop_reject_service_request(const struct HopNode *node, const uint8_t *request_id);

// Poll hops:// service responses sealed back to this node (caller side). Invokes
// `sink(ctx, from32, for_request_id32, status, body_ptr, body_len)` per response. Returning true is
// synchronous acceptance. Returning false leaves the durable row queued for redelivery until
// [`hop_accept_service_response`] succeeds.
void hop_poll_service_responses(const struct HopNode *node,
                                bool (*sink)(void *ctx,
                                             const uint8_t *from,
                                             const uint8_t *for_request_id,
                                             uint16_t status,
                                             const uint8_t *body,
                                             uintptr_t body_len),
                                void *ctx);

// Durably accept one response previously returned by [`hop_poll_service_responses`].
// `request_id` is the 32-byte `for_request_id` supplied to the callback. Returns false for NULL, an
// unknown/already-accepted request id, or a persistence failure.
bool hop_accept_service_response(const struct HopNode *node, const uint8_t *request_id);

// Register (host) an `hps://` topic at `path`, minting and persisting its keys. `kind` is a
// [`HopHpsKind`] discriminant, `access` a [`HopHpsAccess`], `visibility` a [`HopHpsVisibility`],
// each as a plain `uint32_t`.
//
// A `Service` topic has a public key (only the owner broadcasts, signed by it); a `Channel` has
// none (writers sign with their own identity). So the key is written to `out_pubkey` (`out_pubkey_cap`
// bytes, may be NULL to ignore) and its length to `out_pubkey_len` (may be NULL); a channel writes
// zero bytes. The bool return, not the length, is what says whether registration happened: returns
// false on a NULL node/path, an out-of-range `kind`/`access`/`visibility`, or a key that does not
// fit in `out_pubkey_cap`.
bool hop_hps_register(const struct HopNode *node,
                      const char *path,
                      uint32_t kind,
                      uint32_t access,
                      uint32_t visibility,
                      uint8_t *out_pubkey,
                      uintptr_t out_pubkey_cap,
                      uintptr_t *out_pubkey_len);

// Subscribe to `hps://{host}/{path}`: seal a keys request to `host` (32 bytes), which for an `Open`
// topic replies with the topic keys, for `RequestToJoin` queues us for approval, and for `Invite`
// ignores us. Publications then arrive via [`hop_poll_hps_messages`]. Writes the 32-byte subscribe
// bundle id to `out_id` (may be NULL) and returns true.
bool hop_hps_subscribe(const struct HopNode *node,
                       const uint8_t *host,
                       const char *path,
                       uint8_t *out_id);

// Publish `body` to a topic we host or (for a channel) belong to: encrypted once to the topic's
// content key, signed by the service key for a service or by our own identity for a channel, and
// flooded once to every subscriber. Writes the 32-byte bundle id to `out_id` (may be NULL).
// Returns false for an unknown path, a body over [`MAX_C_ABI_INPUT_BYTES`], or no write access.
bool hop_hps_publish(const struct HopNode *node,
                     const char *path,
                     const uint8_t *body,
                     uintptr_t body_len,
                     uint8_t *out_id);

// Drain received `hps://` publications (poll model, the same shape as [`hop_poll_inbox`]). Invokes
// `sink(ctx, id32, path_cstr, sender32, body_ptr, body_len)` once per publication during this call.
// `id` and `sender` each point at 32 bytes; `path` is a NUL-terminated UTF-8 string; every pointer
// is valid only for the callback, so copy what you keep. `sender` is the VERIFIED writer for a
// channel and the host for a service. Returning true is synchronous host acceptance: core then
// durably removes that publication. Returning false leaves it queued for redelivery until
// [`hop_accept_hps_message`] succeeds.
void hop_poll_hps_messages(const struct HopNode *node, bool (*sink)(void *ctx,
                                                                    const uint8_t *id,
                                                                    const char *path,
                                                                    const uint8_t *sender,
                                                                    const uint8_t *body,
                                                                    uintptr_t body_len), void *ctx);

// Durably accept one publication previously returned by [`hop_poll_hps_messages`]. `id` points to
// exactly 32 bytes. Returns false for NULL, an unknown/already-accepted id, or a persistence failure.
bool hop_accept_hps_message(const struct HopNode *node,
                            const uint8_t *id);

// Host to destination: invite `dest` (32 bytes) to a topic we host, the `Invite`-mode key handoff.
// The invite arrives at `dest` via [`hop_poll_hps_invites`]; keys are only sealed once it accepts.
// Writes the 32-byte invite bundle id to `out_id` (may be NULL).
bool hop_hps_invite(const struct HopNode *node,
                    const char *path,
                    const uint8_t *dest,
                    uint8_t *out_id);

// Member to host: accept an invite we received, after which the host seals us the topic keys.
// `host` is 32 bytes. Writes the 32-byte accept bundle id to `out_id` (may be NULL).
bool hop_hps_accept_invite(const struct HopNode *node,
                           const uint8_t *host,
                           const char *path,
                           uint8_t *out_id);

// Decline a received invite. This is DURABLE: the invite is dropped from storage so it does not
// reappear after a restart. `host` is 32 bytes. Returns false on NULL args.
bool hop_hps_decline_invite(const struct HopNode *node, const uint8_t *host, const char *path);

// Drain invites we have received, clearing them. Invokes `sink(ctx, host32, path_cstr, kind)` once
// per invite, where `kind` is a [`HopHpsKind`] discriminant. Pointers are valid only for the
// callback. Unlike the publication queue this is a take-and-clear drain, not an accept-to-remove
// one: an invite the host does not act on is gone, so persist what you surface.
void hop_poll_hps_invites(const struct HopNode *node, void (*sink)(void *ctx,
                                                                   const uint8_t *host,
                                                                   const char *path,
                                                                   uint32_t kind), void *ctx);

// Member to host: leave a topic, so the host stops re-keying us on rotation. Writes the 32-byte
// leave bundle id to `out_id` (may be NULL) and sets `*out_has_id` (may be NULL) to whether there
// was one: leaving a topic we HOST sends no bundle, which is a success with no id rather than a
// failure. Returns false only on NULL args or a core error.
bool hop_hps_leave(const struct HopNode *node, const char *path, uint8_t *out_id, bool *out_has_id);

// Host: the join requests queued on a `RequestToJoin` topic, each a requester address. Invokes
// `sink(ctx, addr32)` once per requester (may be NULL to just count) and returns the count.
uintptr_t hop_hps_pending(const struct HopNode *node,
                          const char *path,
                          void (*sink)(void *ctx, const uint8_t *addr),
                          void *ctx);

// Host: approve a pending requester (32 bytes), sealing them the topic keys. Writes the 32-byte
// keys bundle id to `out_id` (may be NULL).
bool hop_hps_approve(const struct HopNode *node,
                     const char *path,
                     const uint8_t *requester,
                     uint8_t *out_id);

// Host: deny a pending requester (32 bytes) and drop the request. No keys are sealed.
bool hop_hps_deny(const struct HopNode *node, const char *path, const uint8_t *requester);

// Host: selective forward rotation, which is how a member is REVOKED. Mints a new content key and
// seals it to every retained member except the `remove_count` addresses packed back to back in
// `remove` (32 bytes each, so `remove_count * 32` bytes read); a removed member keeps only the dead
// key, so it can still read history it already has and nothing published afterwards. `new_path`
// empty (or NULL) keeps the same path; a non-empty one moves the topic. Invokes `sink(ctx, id32)`
// once per rekey bundle (may be NULL) and returns the count, or 0 on NULL args, an over-long
// `remove` array, or a core error.
intptr_t hop_hps_rekey(const struct HopNode *node,
                       const char *path,
                       const char *new_path,
                       const uint8_t *remove,
                       uintptr_t remove_count,
                       void (*sink)(void *ctx, const uint8_t *id),
                       void *ctx);

// Host: a topic's reach, the number of distinct addresses that have acked a publication on it. This
// is the delivery sense for a flood: there is no per-recipient receipt, so reach is what a UI can
// honestly show. 0 on NULL args or an unknown path.
uint32_t hop_hps_reach(const struct HopNode *node, const char *path);

// Host: the retained-member set for a topic. Invokes `sink(ctx, addr32)` once per member (may be
// NULL to just count) and returns the count.
uintptr_t hop_hps_members(const struct HopNode *node,
                          const char *path,
                          void (*sink)(void *ctx, const uint8_t *addr),
                          void *ctx);

// Every topic this node hosts or follows, so an app can rebuild its channel list after a restart:
// the node persists topics, the app's in-memory list does not. Invokes
// `sink(ctx, host32, path_cstr, kind, hosting, access)` once per topic (may be NULL to just count),
// where `kind` is a [`HopHpsKind`] and `access` a [`HopHpsAccess`] discriminant. Returns the count.
uintptr_t hop_hps_my_topics(const struct HopNode *node, void (*sink)(void *ctx,
                                                                     const uint8_t *host,
                                                                     const char *path,
                                                                     uint32_t kind,
                                                                     bool hosting,
                                                                     uint32_t access), void *ctx);

// Same-app discoverable topics seen on the mesh: the descriptors a `Discoverable` host broadcasts,
// decrypted with the app secret, so this only ever surfaces topics from the same app fabric.
// Invokes `sink(ctx, host32, path_cstr, kind, title_cstr, summary_cstr, access)` once per topic
// (may be NULL to just count) and returns the count.
uintptr_t hop_hps_browse(const struct HopNode *node, void (*sink)(void *ctx,
                                                                  const uint8_t *host,
                                                                  const char *path,
                                                                  uint32_t kind,
                                                                  const char *title,
                                                                  const char *summary,
                                                                  uint32_t access), void *ctx);

// Encode a 32-byte `addr` as base58 into the C buffer `out` (`out_cap` bytes incl. NUL). Returns
// the string length (excluding NUL), or 0 on NULL / insufficient capacity.
uintptr_t hop_address_to_base58(const uint8_t *addr, char *out, uintptr_t out_cap);

// Decode a base58 address C string `text` into `out32` (32 bytes). Returns true iff it decoded to
// exactly 32 bytes.
bool hop_address_from_base58(const char *text, uint8_t *out32);

// Send a message to the 32-byte address `dst`, untraceable by default (DESIGN.md §39).
// `content_type` is a UTF-8 C string (e.g. "text/plain"); `body`/`body_len` is the payload. If
// `request_ack`, a private delivery confirmation is requested. On success writes the 32-byte
// bundle id into `out_id` (room for 32 bytes, may be NULL to ignore) and returns true.
bool hop_send_message(const struct HopNode *node,
                      const uint8_t *dst,
                      const char *content_type,
                      const uint8_t *body,
                      uintptr_t body_len,
                      bool request_ack,
                      uint8_t *out_id);

// Sign a self-certifying reachability record for THIS node's address, binding it to `endpoint`
// (UTF-8 C string, e.g. "wss://myaddress.com/_hop") for `ttl_secs`. Invokes `sink(ctx, bytes, len)`
// once with the signed record bytes (serve at /.well-known/hop or gossip). No-op on NULL args.
void hop_sign_reach_record(const struct HopNode *node,
                           const char *endpoint,
                           uint32_t ttl_secs,
                           void (*sink)(void *ctx, const uint8_t *bytes, uintptr_t len),
                           void *ctx);

// Verify a reachability record. `now_secs` = current Unix time to enforce expiry (0 skips the expiry
// check). Returns true iff valid; on a valid record invokes `sink(ctx, address32, endpoint_cstr,
// issued_at, ttl_secs)` once. Self-certifying: the record is checked against the address it names,
// no external anchor. `bytes`/`len` is the record from `hop_sign_reach_record`.
bool hop_verify_reach_record(const uint8_t *bytes,
                             uintptr_t len,
                             uint64_t now_secs,
                             void (*sink)(void *ctx,
                                          const uint8_t *address,
                                          const char *endpoint,
                                          uint64_t issued_at,
                                          uint32_t ttl_secs),
                             void *ctx);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HOP_H */
